name: ci
on: 
  push:
    branches:
    - main
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run : flutter analyze
    
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run : flutter test --coverage
    - name: Very Good Coverage
      uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
      with:
        path: './coverage/lcov.info'
        min_coverage: 80
