name: testflow
on: 
  push:
    branches:
    - '*'
    - 'feature/*'
    - 'design/*'
    - 'bugfix/*'
    - 'hotfix/*'
    - 'fix/*'
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run : flutter analyze

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run : flutter test --concurrency=1 --coverage
